### ISSUE TITLE
The versioning problem of alto

### ISSUE THREAD

**Issue by itslychee** [itslychee/alto#8]
The project alto was originally meant to be a useful music organizer and so it is as of today, but I received a suggestion from the [Unofficial Go Discord](https://discord.gg/golang) to make the DSL's API publicly available, which so I did and from the looks of [this](https://go.dev/doc/modules/version-numbers) it seems that the semantic versioning format is mandatory, or highly recommended.

This creates somewhat of a logical problem:

1. How should I incorporate changes in the CLI packages when it doesn't adversely affect the compatibility of the DSL API, because a new release makes the user think that there has been changes within the API's code when there hasn't
2. Above applies inversely to the DSL changes as well, but not as bad because the CLI package is dependent on the DSL.

This could be avoided by simply requiring the user to install the binary via Go's CLI, but from my own personal experience it's somewhat tedious to install Go's ~132MB package to create such an alto binary that is around 1-2MBs. I was once a person who had very limited and slow internet and saving every byte of my data usage counted, and once I got good internet I made a vow to myself that I would try to help out those who were like me by ensuring that they can download the least amount of bytes from software releases I would make in the future. Slow internet sucks and I want to help out those with it in any way I can.

Separate versioning ***could work*** for this, and can ensure backwards compatibility with the previous releases which would be ideal. A trivial idea that is, but stress tends to affect the mind. However I do not have a solid idea of how I would implement version branching but I could probably intertwine the major number of the DSL together with the CLI versioning, as the current branching scheme is using major versions for good, obvious reasons.

I will comment the new versioning scheme alto will use after I take some time and carefully think about it. Suggestions are appreciated

**Comment by ItsLychee** [comment]
I believe that the CLI should go by a `MAJOR.CHANGES` system

Where:
- `MAJOR` is the major version of the DSL, ensuring that changes among both packages can remain on the same branch
- `CHANGES` is the number of changes since the last major release of the DSL

Examples:
- `2.0` represents the CLI release version of the 2nd DSL major release, so `2.0.0` and `2.0` would be the same here
- `2.3` represents that there has been 3 CLI releases since the 2nd DSL major release
